# Generated by Django 4.1.1 on 2023-01-12 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentShowdetail3',
            fields=[
                ('std_code', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('tittle_name_lth', models.CharField(blank=True, max_length=20, null=True)),
                ('title_name_len', models.CharField(blank=True, max_length=20, null=True)),
                ('fname_th', models.CharField(blank=True, max_length=255, null=True)),
                ('lname_th', models.CharField(blank=True, max_length=255, null=True)),
                ('fname_en', models.CharField(blank=True, max_length=255, null=True)),
                ('lname_en', models.CharField(blank=True, max_length=255, null=True)),
                ('major_th', models.CharField(blank=True, max_length=100, null=True)),
                ('major_en', models.CharField(blank=True, max_length=100, null=True)),
                ('department_th', models.CharField(blank=True, max_length=100, null=True)),
                ('department_en', models.CharField(blank=True, max_length=100, null=True)),
                ('advisor_id', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'student_showdetail3',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dname_th', models.CharField(max_length=50)),
                ('dname_en', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname_th', models.CharField(max_length=50)),
                ('lname_th', models.CharField(max_length=50)),
                ('fname_en', models.CharField(max_length=50)),
                ('lname_en', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.department')),
            ],
        ),
        migrations.CreateModel(
            name='major',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mname_th', models.CharField(max_length=50)),
                ('mname_en', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_is_graduated', models.BooleanField(default=False)),
                ('student_code', models.IntegerField()),
                ('fname_th', models.CharField(max_length=50)),
                ('lname_th', models.CharField(max_length=50)),
                ('fname_en', models.CharField(max_length=50)),
                ('lname_en', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('advisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.instructor')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.department')),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.major')),
            ],
            options={
                'ordering': ['student_code'],
            },
        ),
    ]
