# Generated by Django 4.1.1 on 2023-01-12 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_authinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authinfo',
            name='user',
            field=models.CharField(max_length=255),
        ),
    ]
