# Generated by Django 4.1.1 on 2023-01-13 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_authinfo_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelForAPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('desc', models.TextField(blank=True, null=True)),
                ('auth_key', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.BooleanField(default=False)),
                ('user', models.CharField(max_length=255)),
            ],
        ),
    ]
