# Generated by Django 4.1.1 on 2023-01-14 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_channelforapi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channelforapi',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
