# Generated by Django 4.1.1 on 2023-01-14 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_alter_channelforapi_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channelforapi',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
