# Generated by Django 4.1.1 on 2023-01-20 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_alter_channelforapi_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='authinfo',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
