# Generated by Django 4.1.7 on 2023-03-07 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EngrDepartment',
            fields=[
                ('departmentid', models.IntegerField(primary_key=True, serialize=False)),
                ('departmentname', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'engr_department',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EngrLeveleducation',
            fields=[
                ('levelid', models.IntegerField(primary_key=True, serialize=False)),
                ('levelname', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'engr_leveleducation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EngrProvince',
            fields=[
                ('idprovince', models.IntegerField(primary_key=True, serialize=False)),
                ('province', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'engr_province',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EngrTitleacademic',
            fields=[
                ('titleacaid', models.IntegerField(primary_key=True, serialize=False)),
                ('titleacafullt', models.CharField(max_length=50)),
                ('titleacafulle', models.CharField(max_length=50)),
                ('titleacalitt', models.CharField(max_length=20)),
                ('titleacalite', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'engr_titleacademic',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EngrTitlename',
            fields=[
                ('titleid', models.IntegerField(primary_key=True, serialize=False)),
                ('title_name_t', models.CharField(db_collation='utf8mb4_unicode_ci', max_length=50)),
                ('title_name_e', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'engr_titlename',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExtPerson',
            fields=[
                ('personid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('title', models.IntegerField(blank=True, null=True)),
                ('fname_t', models.CharField(blank=True, max_length=255, null=True)),
                ('lname_t', models.CharField(blank=True, max_length=255, null=True)),
                ('fname_e', models.CharField(blank=True, max_length=255, null=True)),
                ('lname_e', models.CharField(blank=True, max_length=255, null=True)),
                ('department', models.IntegerField(blank=True, null=True)),
                ('username', models.CharField(blank=True, max_length=15, null=True)),
                ('idcard', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('dateadd', models.DateTimeField(blank=True, null=True)),
                ('bankaccountid', models.CharField(blank=True, max_length=20, null=True)),
                ('bankname', models.CharField(blank=True, max_length=255, null=True)),
                ('taxid', models.CharField(blank=True, max_length=30, null=True)),
                ('peopleid', models.CharField(blank=True, max_length=50, null=True)),
                ('socialid', models.CharField(blank=True, max_length=20, null=True)),
                ('grp', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'ext_person',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FinPersontax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField(db_column='No')),
                ('fullname', models.CharField(db_collation='utf8mb3_general_ci', db_column='FullName', max_length=100)),
                ('dept', models.IntegerField(blank=True, db_column='Dept', null=True)),
                ('staffid', models.CharField(db_column='StaffID', max_length=11)),
                ('summoney', models.FloatField(blank=True, db_column='SumMoney', null=True)),
                ('sumtax', models.FloatField(db_column='SumTAX')),
                ('sumsocial', models.FloatField(db_column='SumSocial')),
                ('socialid', models.CharField(blank=True, db_column='SocialID', max_length=20, null=True)),
                ('y', models.CharField(db_column='Y', max_length=11)),
                ('peapleid', models.CharField(blank=True, db_column='PeapleID', max_length=20, null=True)),
            ],
            options={
                'db_table': 'fin-persontax',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FinPersontaxref',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('y', models.IntegerField(db_column='Y')),
                ('dateput', models.CharField(db_collation='utf8mb3_general_ci', db_column='DatePut', max_length=50)),
            ],
            options={
                'db_table': 'fin-persontaxref',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FinTransfermoney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autokey', models.FloatField()),
                ('staffid', models.CharField(blank=True, db_collation='utf8mb3_unicode_ci', max_length=10, null=True)),
                ('item', models.CharField(blank=True, db_collation='utf8mb3_unicode_ci', max_length=255, null=True)),
                ('money', models.FloatField(blank=True, null=True)),
                ('moneypay', models.FloatField(blank=True, null=True)),
                ('tax', models.CharField(blank=True, db_collation='utf8mb3_unicode_ci', max_length=10, null=True)),
                ('datepay', models.DateField(blank=True, null=True)),
                ('datetax', models.DateField(blank=True, null=True)),
                ('datesocial', models.DateField(blank=True, null=True)),
                ('socialpay', models.FloatField(blank=True, null=True)),
                ('staffidtransfer', models.CharField(blank=True, db_collation='utf8mb3_unicode_ci', max_length=10, null=True)),
                ('tubankitem', models.FloatField(blank=True, null=True)),
                ('office_acc', models.CharField(blank=True, max_length=255, null=True)),
                ('tubankpay', models.FloatField(blank=True, null=True)),
                ('fund', models.FloatField(blank=True, db_column='Fund', null=True)),
                ('waterelec', models.FloatField(blank=True, db_column='WaterElec', null=True)),
                ('chawporkor', models.FloatField(blank=True, null=True)),
                ('assetoffice', models.FloatField(blank=True, null=True)),
                ('water', models.FloatField(blank=True, null=True)),
                ('fundadd', models.FloatField(blank=True, null=True)),
                ('socialadd', models.FloatField(blank=True, null=True)),
                ('notice', models.TextField(blank=True, db_collation='utf8mb3_unicode_ci', null=True)),
                ('type', models.CharField(blank=True, max_length=20, null=True)),
                ('houserent', models.CharField(blank=True, max_length=20, null=True)),
                ('slf', models.FloatField(blank=True, db_column='SLF', null=True)),
                ('icl', models.FloatField(blank=True, db_column='ICL', null=True)),
            ],
            options={
                'db_table': 'fin-transfermoney',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PerPerson',
            fields=[
                ('personid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('title', models.IntegerField(blank=True, null=True)),
                ('fname_t', models.CharField(blank=True, max_length=255, null=True)),
                ('lname_t', models.CharField(blank=True, max_length=255, null=True)),
                ('fname_e', models.CharField(blank=True, max_length=255, null=True)),
                ('lname_e', models.CharField(blank=True, max_length=255, null=True)),
                ('department', models.IntegerField(blank=True, null=True)),
                ('title_academic', models.IntegerField(blank=True, null=True)),
                ('ad_user', models.CharField(blank=True, max_length=15, null=True)),
                ('full_ad', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'per_person',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PerPersonAddress',
            fields=[
                ('personid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('curid', models.CharField(blank=True, max_length=255, null=True)),
                ('curroad', models.CharField(blank=True, max_length=255, null=True)),
                ('cursub', models.CharField(blank=True, max_length=255, null=True)),
                ('curdis', models.CharField(blank=True, max_length=255, null=True)),
                ('curpro', models.CharField(blank=True, max_length=3, null=True)),
                ('curcountry', models.CharField(blank=True, max_length=255, null=True)),
                ('curpost', models.CharField(blank=True, max_length=6, null=True)),
                ('curtel', models.CharField(blank=True, max_length=20, null=True)),
                ('curmobile', models.CharField(blank=True, max_length=20, null=True)),
                ('homeid', models.CharField(blank=True, max_length=255, null=True)),
                ('homeroad', models.CharField(blank=True, max_length=255, null=True)),
                ('homesub', models.CharField(blank=True, max_length=255, null=True)),
                ('homedis', models.CharField(blank=True, max_length=255, null=True)),
                ('homepro', models.CharField(blank=True, max_length=3, null=True)),
                ('homecountry', models.CharField(blank=True, max_length=255, null=True)),
                ('homepost', models.CharField(blank=True, max_length=6, null=True)),
                ('hometel', models.CharField(blank=True, max_length=20, null=True)),
                ('homemobile', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'per_person_address',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PerPersonDetail',
            fields=[
                ('personid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('idcard', models.CharField(blank=True, max_length=13, null=True)),
                ('birthdate', models.CharField(blank=True, max_length=10, null=True)),
                ('sex', models.CharField(blank=True, max_length=1, null=True)),
                ('taxid', models.CharField(blank=True, max_length=15, null=True)),
                ('socialid', models.CharField(blank=True, max_length=15, null=True)),
                ('citizenship', models.CharField(blank=True, max_length=15, null=True)),
                ('nationality', models.CharField(blank=True, max_length=15, null=True)),
                ('religion', models.CharField(blank=True, max_length=15, null=True)),
                ('extelphone', models.CharField(blank=True, max_length=15, null=True)),
                ('rooms', models.CharField(blank=True, max_length=10, null=True)),
                ('stayat', models.CharField(blank=True, max_length=15, null=True)),
                ('cardstatus', models.CharField(blank=True, max_length=1, null=True)),
                ('workstatus', models.CharField(blank=True, max_length=2, null=True)),
                ('typeperson', models.CharField(blank=True, max_length=5, null=True)),
                ('positionid', models.CharField(blank=True, max_length=10, null=True)),
                ('status', models.CharField(blank=True, max_length=1, null=True)),
                ('bankid', models.CharField(blank=True, max_length=20, null=True)),
                ('bankname', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('groupsalary', models.CharField(blank=True, max_length=5, null=True)),
                ('docrefer', models.CharField(blank=True, max_length=255, null=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('codeajarn', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'per_person_detail',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PerPersonEducation',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('personid', models.CharField(blank=True, max_length=10, null=True)),
                ('edulevel', models.CharField(blank=True, db_collation='utf8mb3_unicode_ci', max_length=2, null=True)),
                ('eduname', models.CharField(blank=True, db_collation='utf8mb3_unicode_ci', max_length=255, null=True)),
                ('educer', models.CharField(blank=True, db_collation='utf8mb3_unicode_ci', max_length=255, null=True)),
                ('edumajor', models.CharField(blank=True, db_collation='utf8mb3_unicode_ci', max_length=255, null=True)),
                ('edustart', models.CharField(blank=True, db_collation='utf8mb3_unicode_ci', max_length=10, null=True)),
                ('eduend', models.CharField(blank=True, db_collation='utf8mb3_unicode_ci', max_length=10, null=True)),
                ('edugpa', models.CharField(blank=True, db_collation='utf8mb3_unicode_ci', max_length=5, null=True)),
            ],
            options={
                'db_table': 'per_person_education',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PerPersonExperience',
            fields=[
                ('iddoc', models.IntegerField(primary_key=True, serialize=False)),
                ('personid', models.CharField(blank=True, db_collation='utf8mb3_unicode_ci', max_length=10, null=True)),
                ('name', models.CharField(blank=True, db_collation='utf8mb3_unicode_ci', max_length=255, null=True)),
                ('address', models.TextField(blank=True, db_collation='utf8mb3_unicode_ci', null=True)),
                ('position', models.CharField(blank=True, db_collation='utf8mb3_unicode_ci', max_length=255, null=True)),
                ('start', models.CharField(blank=True, db_collation='utf8mb3_unicode_ci', max_length=10, null=True)),
                ('end', models.CharField(blank=True, db_collation='utf8mb3_unicode_ci', max_length=10, null=True)),
                ('jobdis', models.TextField(blank=True, db_collation='utf8mb3_unicode_ci', null=True)),
            ],
            options={
                'db_table': 'per_person_experience',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PerPersonFamily',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('personid', models.CharField(blank=True, max_length=10, null=True)),
                ('relation', models.CharField(blank=True, max_length=10, null=True)),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('idcard', models.CharField(blank=True, max_length=15, null=True)),
                ('birthday', models.CharField(blank=True, max_length=10, null=True)),
                ('cerid', models.CharField(blank=True, max_length=15, null=True)),
                ('remark', models.CharField(blank=True, max_length=10, null=True)),
                ('medical', models.CharField(blank=True, max_length=3, null=True)),
                ('school', models.CharField(blank=True, max_length=3, null=True)),
                ('job1', models.CharField(blank=True, max_length=255, null=True)),
                ('job2', models.CharField(blank=True, max_length=255, null=True)),
                ('where1', models.CharField(blank=True, max_length=255, null=True)),
                ('where2', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'per_person_family',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PerPersonIngov',
            fields=[
                ('personid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('govid', models.CharField(blank=True, max_length=10, null=True)),
                ('levelc', models.CharField(blank=True, max_length=20, null=True)),
                ('leveledu', models.CharField(blank=True, max_length=20, null=True)),
                ('applywork', models.CharField(blank=True, max_length=100, null=True)),
                ('startwork', models.CharField(blank=True, max_length=100, null=True)),
                ('applyfac', models.CharField(blank=True, max_length=100, null=True)),
                ('startfac', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'per_person_ingov',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PerPersonTraining',
            fields=[
                ('iddoc', models.IntegerField(primary_key=True, serialize=False)),
                ('personid', models.CharField(blank=True, db_collation='utf8mb3_general_ci', max_length=10, null=True)),
                ('typecourse', models.CharField(blank=True, db_collation='utf8mb3_general_ci', max_length=2, null=True)),
                ('titlename', models.TextField(blank=True, db_collation='utf8mb3_general_ci', null=True)),
                ('place', models.TextField(blank=True, db_collation='utf8mb3_general_ci', null=True)),
                ('start', models.CharField(blank=True, db_collation='utf8mb3_general_ci', max_length=10, null=True)),
                ('end', models.CharField(blank=True, db_collation='utf8mb3_general_ci', max_length=10, null=True)),
                ('deptowner', models.TextField(blank=True, db_collation='utf8mb3_general_ci', null=True)),
                ('expense', models.TextField(blank=True, db_collation='utf8mb3_general_ci', null=True)),
                ('source', models.TextField(blank=True, db_collation='utf8mb3_general_ci', null=True)),
                ('dateadd', models.CharField(blank=True, db_collation='utf8mb3_general_ci', max_length=10, null=True)),
                ('timeadd', models.CharField(blank=True, db_collation='utf8mb3_general_ci', max_length=10, null=True)),
            ],
            options={
                'db_table': 'per_person_training',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PerPosition',
            fields=[
                ('prositionid', models.IntegerField(primary_key=True, serialize=False)),
                ('prositionname', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'per_position',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PerStatuswork',
            fields=[
                ('statusworkid', models.IntegerField(primary_key=True, serialize=False)),
                ('statusworkname', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'per_statuswork',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PerTypeperson',
            fields=[
                ('typepersonid', models.IntegerField(primary_key=True, serialize=False)),
                ('typepersonname', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'per_typeperson',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PerTypetraining',
            fields=[
                ('idtype', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('typename', models.CharField(blank=True, db_collation='utf8mb3_general_ci', max_length=255, null=True)),
            ],
            options={
                'db_table': 'per_typetraining',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WebAuthinfo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('secret_key', models.CharField(max_length=255)),
                ('user', models.CharField(max_length=255)),
                ('status', models.IntegerField()),
            ],
            options={
                'db_table': 'web_authinfo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WebChannelforapi',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('desc', models.TextField(blank=True, null=True)),
                ('auth_key', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.IntegerField()),
                ('user', models.CharField(max_length=255)),
                ('limit', models.IntegerField()),
                ('limit_time', models.IntegerField()),
            ],
            options={
                'db_table': 'web_channelforapi',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WebEngrDepartment',
            fields=[
                ('departmentid', models.IntegerField(primary_key=True, serialize=False)),
                ('departmentname', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'web_engr_department',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WebEngrLeveleducation',
            fields=[
                ('levelid', models.IntegerField(primary_key=True, serialize=False)),
                ('levelname', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'web_engr_leveleducation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WebEngrTitlename',
            fields=[
                ('titleid', models.IntegerField(primary_key=True, serialize=False)),
                ('title_name_t', models.CharField(max_length=50)),
                ('title_name_e', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'web_engr_titlename',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WebInstructor',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fname_th', models.CharField(max_length=50)),
                ('lname_th', models.CharField(max_length=50)),
                ('fname_en', models.CharField(max_length=50)),
                ('lname_en', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'web_instructor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WebMajor',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('mname_th', models.CharField(max_length=50)),
                ('mname_en', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'web_major',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WebPerPerson',
            fields=[
                ('personid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('title', models.IntegerField()),
                ('fname_t', models.CharField(max_length=255)),
                ('lname_t', models.CharField(max_length=255)),
                ('fname_e', models.CharField(max_length=255)),
                ('lname_e', models.CharField(max_length=255)),
                ('department', models.IntegerField()),
                ('title_academic', models.IntegerField()),
                ('ad_user', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'web_per_person',
                'managed': False,
            },
        ),
    ]
